name: Import Dataset

on: ["push", "pull_request"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install InvenTree
        run: |
          sudo apt-get install python3-dev python3-pip python3-venv python3-wheel g++
          pip3 install invoke
          git clone --depth 1 https://github.com/inventree/inventree inventree
          cd inventree
          invoke install
